-- AlterTable
ALTER TABLE "Transaction" ALTER COLUMN "amountTransfered" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Wallet" ALTER COLUMN "balance" SET DEFAULT 100000,
ALTER COLUMN "balance" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "WalletMerchant" ALTER COLUMN "balance" SET DEFAULT 100000,
ALTER COLUMN "balance" SET DATA TYPE DOUBLE PRECISION;
